.github/workflows/nodejs.yml

Adds GitHub actions which should automatically test PRs using `npm test`.
Addresses #5, but requires #2 to be merged first before tests will succeed.

Add GitHub actions

---

nuxt.config.js
test/layout/Header.spec.js
test/layout/HeaderTools.spec.js
test/layout/Navigation.spec.js
test/layout/Sidebar.spec.js
test/patternfly/Button.spec.js

Resolves issues brought to light by #7. 
cc: @tylerauerbeck

Fix lint issues

---

components/layout/Navigation.vue
nuxt.config.js
pages/index.vue
pages/one.vue
pages/two.vue
store/index.js

Adds a demo page which proves out frontend-backend communication with authentication working.

Add backend demos

---

package-lock.json
package.json
src/Steps/03_ClusterInformation.jsx
src/Steps/04_LaunchResidency.jsx

With the added extra bonus of dropping 2.1mb from the output JS 📦

fix(slug): format before passing to API

---

.github/workflows/pull-request-checks.yml

Added todos so that work which still needs to be done is not lost... This GitHub workflow is _not finished_, but others need to build using it immediately. I will continue working on it and have another PR up shortly.

GitHub Action Workflow

---

.github/workflows/ci-cd.yml
.github/workflows/pull-request-checks.yml
deployment/Chart.yaml
deployment/templates/deploymentconfig.yaml
deployment/templates/route.yaml
deployment/templates/service.yaml
deployment/values.yaml

Splits the (temporarily merged) GitHub workflow which already existed into PR and master workflows. PR runs checks only, and merge to master runs an S2I build and pushes a new image to Quay.

Improve GitHub workflows

---

README.md
development/Chart.yaml
development/README.md
development/templates/buildconfig.yaml
development/templates/configmap.yaml
development/templates/deploymentconfig.yaml
development/templates/imagestream.yaml
development/templates/route.yaml
development/templates/service.yaml
development/values.yaml

First dev environment commit of the OMP apps

Add development chart

---

README.md
deployment/README.md

PR changes can be viewed here:
https://github.com/oybed/open-management-portal-frontend/blob/readme-update/README.md
@jacobsee @cognizen FYI

Readme update

---

deployment/templates/route.yaml

Route config updated to redirect http requests traffic to https.

http redirect added

---

.github/workflows/pull-request-checks.yml

This starts utilizing a new token that has access to write to discussions

Temporarily disable vulnerability scanning

---

.gitignore
src/routes/router.tsx

[Spencer/Venus] add engagemnt-routing

---

.github/workflows/ci-cd.yml
.gitignore

let lodestar build a container!!!!!!!!!!!!!!!

lodestar ✨

---

src/components/engagement_data_cards/__tests__/__snapshots__/data_cards.spec.tsx.snap
src/components/engagement_data_cards/openshift_cluster_card/openshift_cluster_card.tsx
src/components/engagement_form_fields/oc_version.tsx
src/routes/engagement_details/implementations/__tests__/__snapshots__/engagement_tab_view.spec.tsx.snap

@sdstolworthy not sure if this is 100% complete, but let me know if anything else need to be changed.

Adding the correct use of Labels for OCP input form

---

src/routes/about/__snapshots__/about.spec.tsx.snap
src/routes/about/index.tsx

If "lodestar" is set as a version, display it at the top with a different heading rather than just in the component list

LodeStar App Version Display

---

src/services/factories/service_factory.ts

Hotfix for wrong url being injected into the version service, causing 404 error on fetch.

hotfix for wrong base url being injected to the version service

---

deployment/templates/deploymentconfig.yaml

add ability to tag the e2e with the info that it was initiated by a dc roll from the frontend

Add cypress tag input

---

.github/workflows/ci-cd.yml
.github/workflows/release.yml
deployment/README.md
deployment/values-dev.yaml
deployment/values.yaml

This PR replaces the omp to lodestar in image names. Affects .github/workflows and deployment/values

rename images to lodestar

---

sonar-project.properties

Reverts the sonarcloud token name change

Revert token name change

---

src/common/label_value_tools.ts
src/components/engagement_data_cards/engagement_artifact_card/engagement_artifact_card.tsx
src/components/engagement_edit_modals/__tests__/__snapshots__/openshift_cluster_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/add_artifact_modal.tsx
src/routes/create_new_engagement/__tests__/__snapshots__/create_new_engagement.spec.tsx.snap
src/routes/create_new_engagement/__tests__/create_new_engagement.spec.tsx
src/schemas/engagement.ts
src/schemas/engagement_config.ts
src/schemas/fixtures/engagement_form_config.json
tsconfig.json

Pull artifact types from config rather than an enum in source

Pull artifact types from config #714

---

cypress/integration/1_new_engagement_spec.js

mostly testing for xhr success. reusing the save route.

E2e update

---

src/components/engagement_edit_modals/__tests__/__snapshots__/poc_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/__tests__/poc_edit_modal.spec.tsx
src/components/engagement_edit_modals/point_of_contact_edit_modal.tsx
src/components/engagement_edit_modals/user_row.tsx

Make them lowercase and add validation to them.

Point of contacts emails 

---

cypress/integration/1_new_engagement_spec.js

should fix first set of e2e tests

fix config change from 3 weeks ago

---

cypress/integration/2_existing_engagement_spec.js
cypress/integration/3_navigations_spec.js
cypress/integration/4_about_page_spec.js
src/components/dashboard/widgets/dw_engagement_count.tsx
src/components/dashboard/widgets/engagement_count.spec.tsx

Rabbit holed on this a bit, and ran into some extra issues afterward.

fix (e2e): fixes for dashboard navigation widgets

---

deployment/README.md
deployment/templates/configmap.yaml
deployment/values-dev.yaml

Adds to the configmap in the `deployment` dir so that deploying for dev purposes can have all the necessary json data needed. Adds group / role mapping for sso.

Update Dev ConfigMap

---

src/context/engagement_context/engagement_context.tsx
src/schemas/hosting_environment.ts
src/serializers/engagement/engagement_json_serializer.ts

hosting env uuid

---

cypress/integration/1_new_engagement_spec.js
cypress/support/commands.js
cypress/support/index.js

Simple allow of e2e to pass when uncaught exceptions occur

---

package-lock.json
src/components/dashboard/widgets/dw_last_artifact.tsx
src/components/dashboard/widgets/dw_last_demo.tsx
src/components/dashboard/widgets/dw_last_weekly_report.tsx
src/hocs/with_artifacts.tsx
src/mocks/engagement_mocks.ts
src/packages/api_v1_sdk/apiv1_artifact_service.ts
src/routes/dashboard/index.tsx
src/schemas/engagement.ts

- should display items like 'demo' as 'Demo' by leveraging config service

Use pretty type value for artifacts. Leverage v2 api

---

src/packages/api_v1_sdk/apiv1_summary_count_service.ts

- enables filtering engagement counts by region

filter engagement counts by region

---

src/context/engagement_context/engagement_context.tsx
src/packages/api_v1_sdk/apiv1_engagement_service.ts

The comment in the code is incentive to clean up the code. Leaving it here for a week or 2 just in case another part of the code uses it. It will be logged in the backend if it does (could also check metrics).

get engagement only by uuid. do not use customer / project

---

src/components/engagement_form_fields/use_case.tsx
src/schemas/engagement.ts

- Fix issues where the user experience was very difficult to update use cases.
- Change from TextInput to TextArea to make it visually easier to edit use cases.

fix use case update textinput

---

cypress/support/commands.js
src/packages/api_v1_sdk/apiv1_category_service.ts
src/packages/api_v1_sdk/http_error_handlers.ts

- Hoping cypress likes this token
- Adding back some simplified error handling that breaks the app during e2e tests

Reinsert token in cypress scripts. Re-add some lost error handling

---

.github/workflows/ci-cd.yml
.github/workflows/pull-request-checks.yml
deployment/templates/buildconfig.yaml

- unit tests still pass on 14. after that we need to fix the create new engagement test.

Move from Node 12 to 14

---

src/common/test_state_wrapper.tsx
src/components/customer_select_dropdown/customer_select_dropdown.tsx
src/components/engagement_data_cards/hosting_environment_card/hosting_environment_card.tsx
src/context/engagement_context/__tests__/engagement_context.spec.tsx
src/routes/create_new_engagement/__tests__/create_new_engagement.spec.tsx
src/routes/create_new_engagement/create_new_engagement.tsx

Updates based on test output
- aria-labels added in some places
- createnewengagement now passes on node 16.
- await some acts to avoid warning

update tests and some aria labels. tests pass on node 16

---

src/context/engagement_context/engagement_context.tsx
src/packages/api_v1_sdk/apiv1_engagement_service.ts
src/services/engagement_service/engagement_service_errors.ts

On a `PUT` request to save an engagement
- IF it is a 400 message
- Not a Validation Error (hibernate-validator)
- And contains a `lodestarMessage`
Write that message to the notification system

allow ability to write validation message to the notification system

---

src/app.tsx
src/common/app_features.ts
src/common/human_readable_engagement_field.ts
src/common/version_feature_factory.tsx
src/components/engagement_data_cards/hosting_environment_card/availability_zone_tooltip.tsx
src/components/engagement_data_cards/hosting_environment_card/hosting_environment_card.tsx
src/components/engagement_edit_modals/__tests__/__snapshots__/hosting_environment_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/hosting_environment_edit_modal.tsx
src/components/engagement_form_fields/__tests__/__snapshots__/engagement_form_fields.spec.tsx.snap
src/components/engagement_form_fields/cloud_provider.tsx
src/components/launch_alert_banner/launch_alert_banner.tsx
src/context/engagement_context/engagement_context.tsx
src/context/engagement_context/engagement_hook.tsx
src/packages/api_v1_sdk/apiv1_engagement_service.ts
src/packages/api_v1_sdk/apiv1_version_service.ts
src/packages/api_v1_sdk/client.ts
src/routes/create_new_engagement/create_new_engagement.tsx
src/routes/dashboard/index.tsx
src/routes/engagement/engagement_details.tsx
src/schemas/engagement_config.ts
src/schemas/hosting_environment.ts
src/serializers/engagement/engagement_json_serializer.ts

- New gated feature availability zone (1.3.40)
- Remove deprecated get engagement by cust + proj
- version retrieval without access token

Feature Availability Zone
