.github/workflows/nodejs.yml

This adds linting to our CI process. I've broken it out into a seperate step so it's a bit easier to decipher whether there's an issue with the build process versus formatting. You can see this in action here: https://github.com/tylerauerbeck/omp-fe/commit/ff068a4aba5fc731dda16a3646d2abb8d77208e1/checks
That being said -- looks like there will need to be some cleanup done in linting, but the CI change itself looks to be working as expected.

Add linting to CI

---

.github/workflows/nodejs.yml

This PR adds:
- Linting of markdown for dead-links
- Breaks code linting out into a seperate task for easier detection of failed steps in CI
- Changes `npm` -> `yarn` as described in the README
Follow-up PR will be submitted to improve performance and avoid running `yarn install` and `yarn build` multiple times.
cc/ @jacobsee @mcanoy 
Passing CI example can be seen here: https://github.com/tylerauerbeck/omp-fe/commit/d5616474e818907ecefbb2b9d031192d8fd74345/checks?check_suite_id=305815698

Update linting and add dead-link linter

---

src/components/authentication/private_route.tsx
src/context/session_context.tsx
src/routes/logout/index.tsx
src/routes/router.tsx
src/routes/unauthorized/index.tsx
src/services/authentication_service/implementations/apiv1_auth_service.ts

If a user authenticates successfully but doesn't have the role `manage_projects`, display an unauthorized page directing them to contact the SREs instead of consistently hitting 401s from the backend and kicking the user out.
NOTE: The role name `manage_projects` goes all the way back to proof-of-concept days, and no longer reflects what it does. I think it should be changed both here and in the backend repo, but leaving that for a future edit unless we want to get it done now.

Reject users without access privileges

---

src/components/authentication/send_to_sso.tsx

Keyclock simply forwards this additional param through to Google SSO, so, adding it here seems to be sufficient!

Always display account switcher when using Google login

---

package-lock.json
package.json
src/context/engagement_form_context.tsx
src/routes/engagement_pane/tabs/03_cluster_information.tsx

Automatically generate a subdomain made up of valid characters, 3-8 chars in length, based on project name if it exists, else customer name. If a subdomain has already been set and saved, this should be completely ignored. Only display suggested subdomain if one has not already been set.

Suggest a subdomain based on customer/project name

---

.github/workflows/pull-request-checks.yml

This adds some initial vulnerability scanning and output via the `anchore/scan-action`. What we get from here is knowledge of vulnerabilities prior to merging (and can then extend this to even provide links to CVE, etc.) at a later point or also block/fail things based off of vulnerability level.

Add initial vulnerability scanning check

---

deployment/Chart.yaml
deployment/templates/route.yaml

Rather than having our runtime-config handle the creation of our route, this will now add the route creation to our helm chart. This also bumps the Helm chart to use Helm 3

 Have Helm chart create initial route

---

README.md

The README should always document available runtime configuration options. This PR updates the README with the missing ones.

Adding/updating FE runtime config options

---

cypress/fixtures/users.json
cypress/integration/1_new_engagement_spec.js
src/components/engagement_edit_modals/__tests__/__snapshots__/engagement_summary_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/__tests__/__snapshots__/openshift_cluster_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/engagement_summary_edit_modal.tsx
src/components/engagement_edit_modals/openshift_cluster_edit_modal.tsx
src/components/engagement_edit_modals/user_row.tsx

Updates e2e tests to help get them passing.
- adds fixture for user data
- adds moving dates so that the engagement is active at the end
- checks that the `PUT` completes successfully for users additions
More assertions and tests are needed but this will (should?) get the passing.
In the future I would be interested to track config data that is somewhat out of control and support multiple envs (maybe they already do)

e2e test updates

---

src/routes/dashboard/index.tsx

I followed the rabbit hole down, and it looks like this was already implemented for the most part, except for the actual flagging of the the feature.
Unless there was a previous `newDashboard`? 😆 But it works with the query param.
Also let me know if this PR flow is what you're using.

feature(flag): dashboard components

---

src/common/version_feature_factory.tsx

I missed where we could target specific versions for the flags, and I like that it's the version or above, nice.

fix(flag): target v1.2.0 for dashboards

---

src/components/activity_history_line_item/activity_history_line_item.tsx
src/components/engagement_edit_modals/__tests__/__snapshots__/activity_history_details_modal.spec.tsx.snap

This takes care of opening gitlab URLs in new tabs/windows by default.

Clicking gitlab references in the activity history now opens in new tab

---

src/components/dashboard/widgets/dashboard_people_enabled_card.tsx
src/components/dashboard/widgets/dw_last_updated_engagements.tsx
src/components/dashboard/widgets/people_enabled_chart.tsx

updated 'engagement name' to 'name' on recently updated engagements card, fixed text colors on people enabled card and converted the rollover to %s

cosmetic-fixes

---

README.md
src/common/human_readable_engagement_field.ts
src/components/dashboard/widgets/dw_last_updated_engagements.tsx
src/components/engagement_data_cards/point_of_contact_card/point_of_contact_card.tsx
src/components/engagement_edit_modals/__tests__/__snapshots__/poc_edit_modal.spec.tsx.snap
src/components/engagement_edit_modals/point_of_contact_edit_modal.tsx
src/components/engagement_filter_bar/components/sort_select.tsx

Current version is using a mix of `Client` and `Customer`. This PR attempts to align all uses to be consistent - to use `client`

Changing 'customer' --> 'client' to be consistent

---

.gitignore
cypress/integration/1_new_engagement_spec.js
package-lock.json
package.json
src/packages/api_v1_sdk/client.ts

- Updates the cypress version from 4 to 9.
- adds dayjs as suggested by cypress for tests
- updates expected value for hosting config
- updates api to check if response status is in message. Cypress rejects uncaught exceptions as test failures.

Update cypress version. Fix test hosting option. broken due to config MR

---

cypress/integration/1_new_engagement_spec.js
cypress/support/index.js

- Small e2e change for tests that fail when an http request is aborted
btw - the tests never fail in `s49` but almost never succeed in `test`. why? 🤷

Allow aborted request to fail silently

---

src/assets/css/overrides.css
src/components/activity_history_line_item/activity_history_line_item.tsx
src/components/dashboard/widgets/dw_last_artifact.spec.tsx
src/components/dashboard/widgets/dw_last_demo.spec.tsx
src/components/dashboard/widgets/dw_last_use_cases.spec.tsx
src/components/dashboard/widgets/dw_last_weekly_report.spec.tsx
src/components/engagement_data_cards/__tests__/__snapshots__/timeline_card.spec.tsx.snap
src/components/engagement_data_cards/engagement_artifact_card/engagement_artifact_card.tsx
src/components/engagement_edit_modals/__tests__/__snapshots__/activity_history_details_modal.spec.tsx.snap
src/components/link_or_span/link_or_span.tsx

Make external link icon a little smaller and better aligned, and wrap the last word of the text and link icon in a span with a `nowrap` class to prevent breaking only the icon to a new line.
Tests are... pending.

External link icon updates

---

cypress/support/commands.js
src/index.tsx

For fixing e2e tests.
If not running through Cypress, the `localStorage` checks return null and keycloak will initialize normally.

Initialize keycloak.js directly with token fetched by Cypress

---

deployment/templates/buildconfig.yaml
src/common/engagement_filter_factory.ts
src/components/engagement_filter_bar/__tests__/__snapshots__/engagement_filter_bar.spec.tsx.snap
src/components/engagement_filter_bar/components/engagement_status_select.tsx
src/components/engagement_filter_bar/components/sort_select.tsx
src/components/engagement_filter_bar/components/type_select.tsx
src/components/engagement_filter_bar/engagement_filter_bar.tsx
src/routes/engagement_list/__tests__/__snapshots__/engagement_list_route.spec.tsx.snap
src/routes/engagement_list/engagement_list_route.tsx
src/schemas/engagement_filter.ts

- fixes an issue where viewing the engagement list with urls /upcoming /past or /active - the application requires a double click on the status filter. Now a single click will work (see with `initialFilter`)
- add a new filter by engagement type

fix double click on engagement status. add filter by engagement list

---

src/components/engagement_categories/category_typeahead.tsx
src/components/engagement_categories/engagement_editable_categories.tsx
src/context/category_context/category_context.tsx

- fixes the issue where a user is only getting 20 categories to choose from when selecting existing tags. Now sets to 1000. May not work great as the # of categories grows but patches the existing issue.
Future revisions should look to page from the backend.

allow for more categories to be returned from backend

---

src/routes/create_new_engagement/__tests__/create_new_engagement.spec.tsx
src/routes/create_new_engagement/create_new_engagement.tsx

add timezone on create 
- it will attempt to pull the tz from the users computer
- fallback is UTC (would be rare to not get this for common browsers)

add timezone guess to create new engagement

---

src/components/engagement_data_cards/hosting_environment_card/hosting_environment_card.tsx

In the engagement view, the OCP version is displayed as the `value` rather than the `label` content .. this PR attempts to fix it so the label value is used

Attempting to fix OCP version display
